### ISSUE TITLE
[용어사전] 용어 구분 항목 추가 요청

### ISSUE THREAD

**Issue by sde-sonjihyun** [SportsdataEvolution/ADS#11]
용어사전 관리시 용어들의 속성에 따라 구분 가능하도록 '구분' 항목 추가 요청드립니다.

1. 관리자 페이지에서 '구분' 생성/수정/삭제 가능하도록 수정 요청드립니다.

2. 사용자 페이지에서 용어사전 조회시 구분 항목에 따라 select box로 나누어 조회 가능하도록 수정 요청드립니다.

3. 구분 항목의 그룹 안에서 정렬 순서를 관리자가 지정 가능하도록 수정 요청드립니다.

**Comment by ParkNamil** [comment]
수정되었습니다
