### ISSUE TITLE
[사용자 화면 - 전체 검색 창] 기능 확인 요청

### ISSUE THREAD

**Issue by sde-sonjihyun** [SportsdataEvolution/ADS#12]
사용자 화면 우측 상단에 검색창 내부에 '선수 검색하기' 텍스트 넣어주세요.

![0526_선수 검색하기](https://user-images.githubusercontent.com/82424617/119595212-28ec4f00-be18-11eb-803f-72e0df753fd4.PNG)

현재 검색창에 검색어를 입력해도 아무런 결과가 없습니다.
확인 요청드립니다.

**Comment by ParkNamil** [comment]
수정완료

**Comment by sde-sonjihyun** [comment]
@ParkNamil 
선수 검색시 오류 나옵니다!

![image](https://user-images.githubusercontent.com/82424617/119933611-663f1100-bfbf-11eb-8ea5-c218c189275c.png)

**Comment by ParkNamil** [comment]
수정되었습니다
