### ISSUE TITLE
[네오] 선수분석 > 타자 > 발사각 그래프 문의

### ISSUE THREAD

**Issue by ParkNamil** [SportsdataEvolution/ADS#13]
기획서 상에서 타자의 발사각 그래프 표현시 타구수와 각도의 관계가 이해가 되지 않습니다.
설명 부탁드립니다.

![캡처](https://user-images.githubusercontent.com/84827089/119760835-b8abff00-bee5-11eb-8951-7bbb4bb0ec1d.PNG)

**Comment by sde-sonjihyun** [comment]
발사각도별 타구의 분포를 나타내는 그래프입니다.

예를들어, A타자의 발사각 30도에 총 타구수가 15개 일 때, 발사각(X축):30 / 타구수(Y축):15에 해당하는 좌표를 찍어주시면됩니다.

그리고 총 타구와 별도로 안타(1루타, 2루타, 홈런)를 맞은 타구는 서로 다른 색으로 표시해주시면 됩니다.

**Comment by ParkNamil** [comment]
발사각이 소수점 자리로 나와서 각 타구마다 다른데 어떻게 타구수가 여러개 일 수 있을까요?
발사각의 범위를 두고 타구수를 합계하면 모를까.... 예를 들어 5~15도 구간이면 10도를 x값으로 하고 타구수를 합계한다던지요...
확인바랍니다

**Comment by sde-sonjihyun** [comment]
발사각도 소수점 첫번째 자리에서 반올림하여 정수형으로 계산해주시면됩니다:)

**Comment by sde-sonjihyun** [comment]
X축 발사각 10도 간격 범위로 변경하겠습니다.

(예) 10도~20도, 21도~30도,...

**Comment by ParkNamil** [comment]
수정되었습니다
