### ISSUE TITLE
[사용자 화면 - 회원가입] 입력 항목 추가 요청(비밀번호 확인)

### ISSUE THREAD

**Issue by sde-sonjihyun** [SportsdataEvolution/ADS#14]
사용자 화면에서 회원 가입 입력 항목에 '비밀번호 확인' 입력 필드 추가 요청드립니다.

'비밀번호' 와 '비밀번호 확인' 입력 값이 서로 다를 경우 입력창 하단에 '비밀번호를 확인해주세요' 알림 메시지가 출력되도록 해주세요. 그리고 서로 다를 때 회원가입이 되지 않도록 해주세요,

**Comment by ParkNamil** [comment]
수정완료

**Comment by sde-sonjihyun** [comment]
'비밀번호' 입력값과 '비밀번호 확인'입력 값이 서로 다를 경우 '비밀번호를 확인해주세요' 알림 메시지가 출력되도록 수정 요청드립니다.

그리고 서로 다른 경우 '다음'버튼 선택시 알림창이 표시되고, 회원가입이 진행되지 않도록 해주세요.

**Comment by sde-sonjihyun** [comment]
> 수정완료

'비밀번호' 입력값과 '비밀번호 확인'입력 값이 서로 다를 경우 '비밀번호를 확인해주세요' 알림 메시지가 출력되도록 수정 요청드립니다.

그리고 서로 다른 경우 '다음'버튼 선택시 알림창이 표시되고, 회원가입이 진행되지 않도록 해주세요.

**Comment by ParkNamil** [comment]
수정되었습니다
