### ISSUE TITLE
[훈련장 정보 관리] 훈련장 정보 관리 엑셀 import 양식 전달 요청

### ISSUE THREAD

**Issue by sde-sonjihyun** [SportsdataEvolution/ADS#16]
훈련장 정보 관리 엑셀 import 양식 전달 요청드립니다.

**Comment by ParkNamil** [comment]
훈련장 엑셀등록 양식입니다

[양식_훈련장.xlsx](https://github.com/SportsdataEvolution/ADS/files/6564237/_.xlsx)
