### ISSUE TITLE
[FAQ] FAQ 구분 추가 기능 확인 요청

### ISSUE THREAD

**Issue by sde-sonjihyun** [SportsdataEvolution/ADS#20]
관리자페이지 - 게시판관리 - FAQ 관리 - '구분추가' 선택해 구분 항목을 추가하려고하는데

'추가' 버튼과 '저장' 버튼을 선택해도 아무런 이벤트가 발생하지 않습니다.

확인요청드립니다.

**Comment by ParkNamil** [comment]
수정되었습니다
