### ISSUE TITLE
[FAQ] 게시물 등록 후 목록 조회 화면 수정 요청

### ISSUE THREAD

**Issue by sde-sonjihyun** [SportsdataEvolution/ADS#21]
FAQ 에서 새로운 게시글을 등록하고 저장을 선택했을 때, 현재는 기존에 등록된 내용은 보이지 않고 새롭게 등록된 내용이 출력됩니다.

등록 버튼을 선택하고 저장시 기존에 등록했던 내용들과 함께 출력되도록 수정요청드립니다.

(현재 FAQ관리를 누르면 전체 목록이 출력됩니다!)

**Comment by ParkNamil** [comment]
수정되었습니다
