### ISSUE TITLE
[FAQ] 화면 텍스트 수정 요청

### ISSUE THREAD

**Issue by sde-sonjihyun** [SportsdataEvolution/ADS#23]
관리자페이지 - 게시판관리 - FAQ등록시 
제목 -> 질문
내용 -> 답변

으로 수정요청드립니다.

![image](https://user-images.githubusercontent.com/82424617/120094768-52311600-c15d-11eb-8eab-45f9c04b57b7.png)

**Comment by ParkNamil** [comment]
수정되었습니다
