### ISSUE TITLE
[사용자 화면 - 전체 검색 창] 기능 확인 요청(엔터키)

### ISSUE THREAD

**Issue by sde-sonjihyun** [SportsdataEvolution/ADS#24]
사용자 화면 - 전체 검색 창에 선수 이름 입력 후 엔터키로도 선수 검색 가능하도록 수정 요청드립니다,
(현재 마우스로 검색 버튼 선택시 검색됨)

**Comment by ParkNamil** [comment]
수정되었습니다

**Comment by sde-sonjihyun** [comment]
@ParkNamil 
엔터키 기능 동작 안합니다. 확인부탁드리겠습니다!

**Comment by ParkNamil** [comment]
페이지 리프레시 하고 다시 해보시기 바랍니다
