### ISSUE TITLE
[마이페이지] 회원정보수정 수정 요청

### ISSUE THREAD

**Issue by sde-sonjihyun** [SportsdataEvolution/ADS#25]
사용자화면 - 마이페이지 - 회원정보 수정 화면에서

'아이디' 항목이 중복으로 들어가있습니다.

휴대전화번호로 수정 요청드립니다.

![image](https://user-images.githubusercontent.com/82424617/120095456-0c764c80-c161-11eb-80e7-2b15a5dd2374.png)

**Comment by ParkNamil** [comment]
수정되었습니다
