### ISSUE TITLE
[마이페이지] 텍스트 수정 요청

### ISSUE THREAD

**Issue by sde-sonjihyun** [SportsdataEvolution/ADS#26]
사용자화면 - 마이페이지 텍스트 수정 요청드립니다.

1. 회원가입 -> 마이페이지
2. 주위해 주세요 -> 주의해주세요
![image](https://user-images.githubusercontent.com/82424617/120095606-c79ee580-c161-11eb-9e0e-45e98b921c91.png)

**Comment by ParkNamil** [comment]
수정되었습니다
