### ISSUE TITLE
[회원탈퇴] 회원탈퇴 기능 수정 요청

### ISSUE THREAD

**Issue by sde-sonjihyun** [SportsdataEvolution/ADS#29]
사용자화면 - 마이페이지 - 회원탈퇴시 비밀번호를 입력하고 '확인'버튼을 선택하면 

'회원탈퇴가 완료되었습니다. 그동안 이용해 주셔서 감사합니다.' 알림 창이 출력되고, '확인'버튼을 선택하면 

해당 페이지가 그대로 유지되는데, ADS페이지 첫 화면(로그인 화면)으로 이동하도록 수정요청드립니다.

**Comment by ParkNamil** [comment]
수정되었습니다
