### ISSUE TITLE
[아이디찾기] 알림 화면 내용 수정 요청

### ISSUE THREAD

**Issue by sde-sonjihyun** [SportsdataEvolution/ADS#31]
아이디 찾기 버튼 선택 후 나오는 알림창 메시지의 내용 수정 요청드립니다.

아이디는 user 입니다 -> 찾으시는 아이디는 user 입니다.

![image](https://user-images.githubusercontent.com/82424617/120096268-755fc380-c165-11eb-823a-52b35e93e77e.png)

**Comment by ParkNamil** [comment]
수정되었습니다

**Comment by SportsdataEvolution** [comment]
errer

**Comment by chaudi11** [comment]
test
