### ISSUE TITLE
[회원가입] 회원가입 기능 확인 요청

### ISSUE THREAD

**Issue by sde-sonjihyun** [SportsdataEvolution/ADS#4]
현재 ADS 사용자 페이지에서 회원가입 후 관리자 페이지 - 계정관리 에서 새로 등록한 회원이 확인되지 않습니다.

또한, 관리자페이지 - 계정관리 에서 새로운 회원 등록 기능이 확인되지 않습니다.

**Comment by ParkNamil** [comment]
수정완료

**Comment by sde-sonjihyun** [comment]
관리자 페이지 - 계정관리 목록에서 승인 -> '거절'로 저장했는데 

사용자 페이지에서 로그인이 가능하고, 관리자페이지에 자동으로 '승인'으로 변경되었습니다.

확인요청드립니다.

**Comment by sde-sonjihyun** [comment]
> 수정완료



관리자 페이지 - 계정관리 목록에서 승인 -> '거절'로 저장했는데 

사용자 페이지에서 로그인이 가능하고, 관리자페이지에 자동으로 '승인'으로 변경되었습니다.

확인요청드립니다.

**Comment by ParkNamil** [comment]
수정되었습니다

**Comment by sde-sonjihyun** [comment]
@ParkNamil 

사용자 화면에서 회원가입 완료 후 아래와 같은 오류 화면으로 넘어갑니다. 확인 요청드립니다.
관리자 페이지 - 계정관리에는 회원가입 완료되어 승인 대기 상태로 보여집니다. 

![image](https://user-images.githubusercontent.com/82424617/120094576-0d58af80-c15c-11eb-95a9-30b9173809d3.png)

**Comment by sde-sonjihyun** [comment]
@ParkNamil 

관리자 화면에서 가입한 회원에 대해 '승인'을 선택하면 다음과 같은 오류 메시지가 나타납니다.
확인 요청드립니다.

![image](https://user-images.githubusercontent.com/82424617/120094602-3ed17b00-c15c-11eb-92fa-330a7104bd2e.png)

**Comment by ParkNamil** [comment]
파일을 잘못 올린것 같습니다. 
다시 업로드하고 확인했습니다
