### ISSUE TITLE
[사용자 화면 - 등록현황] 선수/팀 조회시 SELECT BOX 항목에 '전체' 추가 요청

### ISSUE THREAD

**Issue by sde-sonjihyun** [SportsdataEvolution/ADS#5]
사용자페이지 - 등록현황 - 선수/팀 조회시

SELECT BOX에 '전체' 항목 추가 요청드립니다.

(예)
등록현황 - 선수 - 팀 선택 → 전체 추가
등록현황 - 선수 - 포지션 선택 → 전체 추가
등록현황 - 팀 - 지역 선택 → 전체 추가

**Comment by ParkNamil** [comment]
수정완료
