### ISSUE TITLE
[관리자 화면 - 선수 등록] 입력 항목 유효성 검사 추가 요청

### ISSUE THREAD

**Issue by sde-sonjihyun** [SportsdataEvolution/ADS#6]
관리자 페이지 - 소속관리 - 선수관리 - 선수 등록시 입력 항목에 대한 유효성 검사 추가 요청드립니다.

1. '선수명' 항목 숫자 및 특수문자 입력 시 입력창 하단에 알림 문구 표시
(예) 한글과 영문 대/소문자를 입력하세요.

2. '등번호' 항목 숫자를 제외한 문자 입력시 입력창 하단에 알림 문구 표시
(예) 등번호를 다시 확인해주세요.

3. '생년월일' 입력 방식을 사용자 화면 - 회원가입 - 생년월일 입력 방식으로 변경해주세요.

4. '신장' 및 '체중' 항목에 숫자를 제외한 문자 입력시 입력창 하단에 알림 문구 표시
(예) 신장을 다시 확인해주세요.

**Comment by ParkNamil** [comment]
수정완료

**Comment by sde-sonjihyun** [comment]
현재 신장 및 체중에 문자를 입력해도 선수 등록이 가능합니다. 수정 요청드립니다:)

**Comment by sde-sonjihyun** [comment]
> 수정완료

현재 신장 및 체중에 문자를 입력해도 선수 등록이 가능합니다. 수정 요청드립니다:)

**Comment by ParkNamil** [comment]
수정되었습니다
