### ISSUE TITLE
[관리자화면 - 선수 등록] 선수 등록 기능 확인 요청

### ISSUE THREAD

**Issue by sde-sonjihyun** [SportsdataEvolution/ADS#7]
관리자페이지 - 소속관리 - 선수 관리 - 선수 등록 시 

항목 입력 후 '등록' 버튼 선택 시 오류 발생해 확인 요청합니다.

![0526_선수등록 오류](https://user-images.githubusercontent.com/82424617/119591568-cc863100-be11-11eb-9f1d-9c34a535c709.PNG)

**Comment by ParkNamil** [comment]
수정완료
