### ISSUE TITLE
[관리자 화면 - 팀 등록] 입력 항목 유효성 검사 추가 요청

### ISSUE THREAD

**Issue by sde-sonjihyun** [SportsdataEvolution/ADS#8]
관리자페이지 - 소속관리 - 팀 관리 - 팀 등록 시 필수 입력값들이 누락되었을 경우 등록 불가하도록 수정 요청드립니다.

현재 '팀명', '감독', '선수수' 입력하지 않아도 등록 가능한데,

모든 값들이 입력되었을 경우에만 등록 가능하도록 수정해주세요.

**Comment by ParkNamil** [comment]
수정완료

**Comment by sde-sonjihyun** [comment]
현재 팀 등록시 '선수수'항목에 문자 입력 후 등록 버튼을 선택하면 팀 목록이 출력됩니다.

'선수수'항목에 숫자만 입력 가능하도록 수정 요청드립니다:)

**Comment by sde-sonjihyun** [comment]
> 수정완료

현재 팀 등록시 '선수수'항목에 문자 입력 후 등록 버튼을 선택하면 팀 목록이 출력됩니다.

'선수수'항목에 숫자만 입력 가능하도록 수정 요청드립니다:)

**Comment by ParkNamil** [comment]
수정되었습니다
