### ISSUE TITLE
[관리자 화면 - 선수 등록/팀 등록] 엑셀 업로드 양식 전달 요청

### ISSUE THREAD

**Issue by sde-sonjihyun** [SportsdataEvolution/ADS#9]
관리자화면 - 선수 등록 / 팀 등록시 현재 DB 기준으로 엑셀 업로드 가능한 양식 전달 요청드립니다.

기존에 전달받았던 엑셀 양식으로 엑셀 업로드 진행시 선수 등록이 되지 않습니다.

**Comment by ParkNamil** [comment]
양식첨부하여 드립니다

[양식_선수등록.xlsx](https://github.com/SportsdataEvolution/ADS/files/6552179/_.xlsx)
[양식_팀등록.xlsx](https://github.com/SportsdataEvolution/ADS/files/6552181/_.xlsx)
